/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiTestGateRouteImport } from './routes/api.test-gate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestGateRoute = ApiTestGateRouteImport.update({
  id: '/api/test-gate',
  path: '/api/test-gate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/receipts': typeof ReceiptsRoute
  '/rules': typeof RulesRoute
  '/api/$': typeof ApiSplatRoute
  '/api/products': typeof ApiProductsRoute
  '/api/test-gate': typeof ApiTestGateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/receipts': typeof ReceiptsRoute
  '/rules': typeof RulesRoute
  '/api/$': typeof ApiSplatRoute
  '/api/products': typeof ApiProductsRoute
  '/api/test-gate': typeof ApiTestGateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/receipts': typeof ReceiptsRoute
  '/rules': typeof RulesRoute
  '/api/$': typeof ApiSplatRoute
  '/api/products': typeof ApiProductsRoute
  '/api/test-gate': typeof ApiTestGateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/receipts'
    | '/rules'
    | '/api/$'
    | '/api/products'
    | '/api/test-gate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/receipts'
    | '/rules'
    | '/api/$'
    | '/api/products'
    | '/api/test-gate'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/receipts'
    | '/rules'
    | '/api/$'
    | '/api/products'
    | '/api/test-gate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RulesRoute: typeof RulesRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiTestGateRoute: typeof ApiTestGateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-gate': {
      id: '/api/test-gate'
      path: '/api/test-gate'
      fullPath: '/api/test-gate'
      preLoaderRoute: typeof ApiTestGateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ReceiptsRoute: ReceiptsRoute,
  RulesRoute: RulesRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiTestGateRoute: ApiTestGateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
